/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModel"
 * 	found in "Test.asn1"
 */

#ifndef	_AnonSequence_H_
#define	_AnonSequence_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Test2Type.h"
#include "TestType.h"
#include "TestSequence.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AnonSequence */
typedef struct AnonSequence {
	struct sequence1 {
		struct sequence2 {
			TestSequence_t	 sequence3;
			long	 level3;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} sequence2;
		TestType_t	 level2;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} sequence1;
	Test2Type_t	 level1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AnonSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AnonSequence;

#ifdef __cplusplus
}
#endif

#endif	/* _AnonSequence_H_ */
#include <asn_internal.h>
