/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModel"
 * 	found in "Test.asn1"
 */

#include "AnonSequence.h"

static asn_TYPE_member_t asn_MBR_sequence2_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct sequence2, sequence3),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TestSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sequence3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct sequence2, level3),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"level3"
		},
};
static ber_tlv_tag_t asn_DEF_sequence2_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_sequence2_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* level3 at 24 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* sequence3 at 22 */
};
static asn_SEQUENCE_specifics_t asn_SPC_sequence2_specs_3 = {
	sizeof(struct sequence2),
	offsetof(struct sequence2, _asn_ctx),
	asn_MAP_sequence2_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sequence2_3 = {
	"sequence2",
	"sequence2",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sequence2_tags_3,
	sizeof(asn_DEF_sequence2_tags_3)
		/sizeof(asn_DEF_sequence2_tags_3[0]), /* 1 */
	asn_DEF_sequence2_tags_3,	/* Same as above */
	sizeof(asn_DEF_sequence2_tags_3)
		/sizeof(asn_DEF_sequence2_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_sequence2_3,
	2,	/* Elements count */
	&asn_SPC_sequence2_specs_3,	/* Additional specs */
	NULL,	/* Not a primitive */
	NULL,	/* No parent */
	0	/* Not an Anonymous Type */
};

static asn_TYPE_member_t asn_MBR_sequence1_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct sequence1, sequence2),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_sequence2_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sequence2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct sequence1, level2),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_TestType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"level2"
		},
};
static ber_tlv_tag_t asn_DEF_sequence1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_sequence1_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* level2 at 26 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* sequence2 at 22 */
};
static asn_SEQUENCE_specifics_t asn_SPC_sequence1_specs_2 = {
	sizeof(struct sequence1),
	offsetof(struct sequence1, _asn_ctx),
	asn_MAP_sequence1_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sequence1_2 = {
	"sequence1",
	"sequence1",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sequence1_tags_2,
	sizeof(asn_DEF_sequence1_tags_2)
		/sizeof(asn_DEF_sequence1_tags_2[0]), /* 1 */
	asn_DEF_sequence1_tags_2,	/* Same as above */
	sizeof(asn_DEF_sequence1_tags_2)
		/sizeof(asn_DEF_sequence1_tags_2[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_sequence1_2,
	2,	/* Elements count */
	&asn_SPC_sequence1_specs_2,	/* Additional specs */
	NULL,	/* Not a primitive */
	NULL,	/* No parent */
	0	/* Not an Anonymous Type */
};

static asn_TYPE_member_t asn_MBR_AnonSequence_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AnonSequence, sequence1),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_sequence1_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sequence1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AnonSequence, level1),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Test2Type,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"level1"
		},
};
static ber_tlv_tag_t asn_DEF_AnonSequence_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_AnonSequence_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* level1 at 28 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* sequence1 at 24 */
};
static asn_SEQUENCE_specifics_t asn_SPC_AnonSequence_specs_1 = {
	sizeof(struct AnonSequence),
	offsetof(struct AnonSequence, _asn_ctx),
	asn_MAP_AnonSequence_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AnonSequence = {
	"AnonSequence",
	"AnonSequence",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AnonSequence_tags_1,
	sizeof(asn_DEF_AnonSequence_tags_1)
		/sizeof(asn_DEF_AnonSequence_tags_1[0]), /* 1 */
	asn_DEF_AnonSequence_tags_1,	/* Same as above */
	sizeof(asn_DEF_AnonSequence_tags_1)
		/sizeof(asn_DEF_AnonSequence_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AnonSequence_1,
	2,	/* Elements count */
	&asn_SPC_AnonSequence_specs_1,	/* Additional specs */
	NULL,	/* Not a primitive */
	NULL,	/* No parent */
	0	/* Not an Anonymous Type */
};

