/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModel"
 * 	found in "Test.asn1"
 */

#ifndef	_TestSequenceOf_H_
#define	_TestSequenceOf_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TestSequence;

/* TestSequenceOf */
typedef struct TestSequenceOf {
	A_SEQUENCE_OF(struct TestSequence) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestSequenceOf_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestSequenceOf;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TestSequence.h"

#endif	/* _TestSequenceOf_H_ */
#include <asn_internal.h>
