/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModel"
 * 	found in "Test.asn1"
 */

#ifndef	_TestSequence_H_
#define	_TestSequence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include "TestType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TestSequence */
typedef struct TestSequence {
	UTF8String_t	 str;
	TestType_t	 testVar;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestSequence;

#ifdef __cplusplus
}
#endif

#endif	/* _TestSequence_H_ */
#include <asn_internal.h>
