/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModel"
 * 	found in "Test.asn1"
 */

#include "TestSet.h"

static asn_TYPE_member_t asn_MBR_TestSet_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TestSet, testSequence),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TestSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"testSequence"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TestSet, num),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Test2Type,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"num"
		},
};
static ber_tlv_tag_t asn_DEF_TestSet_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TestSet_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* num at 15 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* testSequence at 13 */
};
static uint8_t asn_MAP_TestSet_mmap_1[(2 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (1 << 6)
};
static asn_SET_specifics_t asn_SPC_TestSet_specs_1 = {
	sizeof(struct TestSet),
	offsetof(struct TestSet, _asn_ctx),
	offsetof(struct TestSet, _presence_map),
	asn_MAP_TestSet_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_TestSet_tag2el_1,	/* Same as above */
	2,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_TestSet_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_TestSet = {
	"TestSet",
	"TestSet",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TestSet_tags_1,
	sizeof(asn_DEF_TestSet_tags_1)
		/sizeof(asn_DEF_TestSet_tags_1[0]), /* 1 */
	asn_DEF_TestSet_tags_1,	/* Same as above */
	sizeof(asn_DEF_TestSet_tags_1)
		/sizeof(asn_DEF_TestSet_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TestSet_1,
	2,	/* Elements count */
	&asn_SPC_TestSet_specs_1,	/* Additional specs */
	NULL,	/* Not a primitive */
	NULL,	/* No parent */
	0	/* Not an Anonymous Type */
};

