/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModel"
 * 	found in "Test.asn1"
 */

#ifndef	_Test2Type_H_
#define	_Test2Type_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TestType.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Test2Type */
typedef TestType_t	 Test2Type_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Test2Type;
asn_struct_free_f Test2Type_free;
asn_struct_print_f Test2Type_print;
asn_constr_check_f Test2Type_constraint;
ber_type_decoder_f Test2Type_decode_ber;
der_type_encoder_f Test2Type_encode_der;
xer_type_decoder_f Test2Type_decode_xer;
xer_type_encoder_f Test2Type_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Test2Type_H_ */
#include <asn_internal.h>
