/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModel"
 * 	found in "Test.asn1"
 */

#ifndef	_TestSet_H_
#define	_TestSet_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TestSequence.h"
#include "Test2Type.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum TestSet_PR {
	TestSet_PR_testSequence,	/* Member testSequence is present */
	TestSet_PR_num,	/* Member num is present */
} TestSet_PR;

/* TestSet */
typedef struct TestSet {
	TestSequence_t	 testSequence;
	Test2Type_t	 num;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pTestSet, TestSet_PR_x) */
	unsigned int _presence_map
		[((2+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestSet;

#ifdef __cplusplus
}
#endif

#endif	/* _TestSet_H_ */
#include <asn_internal.h>
