/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModel"
 * 	found in "Test.asn1"
 */

#ifndef	_TestSetOf_H_
#define	_TestSetOf_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TestSequence;

/* TestSetOf */
typedef struct TestSetOf {
	A_SET_OF(struct TestSequence) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestSetOf_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestSetOf;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TestSequence.h"

#endif	/* _TestSetOf_H_ */
#include <asn_internal.h>
